### ISSUE TITLE
use a computer camere

### ISSUE THREAD

**Issue by soufianoxx** [soikat15/OpenCv_Object_distance#1]
Hello @soikat15,
How can I use a computer camera instead of Ip camera ? 
thanks

**Comment by SoikatHasanAhmed** [comment]
Please run the code in default which will capture the video from the webcam ( in your case your computer camera). If you face any problem while running the code, please let me know

**Comment by soufianoxx** [comment]
@soikat15  i have this error :
<<<---- taking calibrating Image ---->>>
Traceback (most recent call last):
  File "C:\Users\Desktop\DM2-FP\OpenCv_Object_distance-master\object_distance.py", line 33, in <module>
    marker = find_marker(c_image)
  File "C:\Users\Desktop\DM2-FP\OpenCv_Object_distance-master\methods.py", line 14, in find_marker
    _, contours, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-qjdp5db9\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

Process finished with exit code 1

**Comment by SoikatHasanAhmed** [comment]
the code has been updated. please check and let me know

**Comment by soufianoxx** [comment]
@soikat15 now this error : 

  File "C:\Users\Desktop\DM2-FP\OpenCv_Object_distance-master\methods.py", line 15, in find_marker
    con = max(contours, key=cv2.contourArea)
ValueError: max() arg is an empty sequence

**Comment by SoikatHasanAhmed** [comment]
Please make sure you have a target object ( in this case blue object ) while initialization.
