### ISSUE TITLE
rgument --webcam: conflicting option string: --webcam

### ISSUE THREAD

**Issue by poptartpudding** [soikat15/OpenCv_Object_distance#2]
Anyone has experienced argument error too? I am currently running on jupyter notebook. 

`parser.add_argument('--webcam', type=bool, default=True)
parser.add_argument('--url', type=str, default='http://192.168.0.4:8080/shot.jpg')
args, unknown = parser.parse_known_args()
args = parser.parse_args()
args = Args(args, unknown) # dict2object
obj = args.copy() # object2dict`

The last two lines are modified by me since i thought the original lines might conflict with jupyter. 
Anyone knows how to modify them so that I could run on jupyter thank you so much!

**Comment by SoikatHasanAhmed** [comment]
Sorry for late reply please try to replace this lines 
```python
parser = argparse.ArgumentParser()
parser.add_argument('--webcam', type=bool, default=True)
parser.add_argument('--url', type=str, default='http://192.168.0.4:8080/shot.jpg')
```
args = parser.parse_args()
with lines 
```python
class Args:
  webcam = True
  url = 'http://192.168.0.4:8080/shot.jpg'

args = Args()
```
